---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ai-hospitality
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: backend

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ai-hospitality
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend
